name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building and pushing image to Docker hub!
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
        run: |
          docker build . --file Dockerfile --tag $DOCKER_ID/pastebin1s-api:latest
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
          docker push $DOCKER_ID/pastebin1s-api:latest
